### ISSUE TITLE
Question : Babel keeps building the wrong module format, what am I missing?

### ISSUE THREAD

**Issue by nosachamos** [milworm/gulp-css-gsub#4]
When I build the lib, I keep getting a module format like this:

```
exports["default"] = function (config) { 
  ...
}
```

instead of:

```
exports.default = function (config) {
   ...
}
```

tried this:

1 - created a .babelrc file at the root of the dir I'm building with this content:

```
{ "presets": ["es2015"] }
```

...then ran the command babel -d lib/ src/ - but got the same output.

I also tried using the gulp (with the gulpfile that comes with the lib) but I continue to get the same issue... what am I missing?

**Comment by milworm** [comment]
I just used `npm run build`. But my question is: 
what's wrong with exports['default']?

**Comment by nosachamos** [comment]
Oh nothing wrong, now that I reread my issue I noticed I explained the problem wrong.. I was actually getting a module format like this `export default ...` which wouldn't run on my environment. I needed your output format. But I solved by telling babel to compile to UMD instead.

Closing this issue. Thanks!

**Comment by milworm** [comment]
Great!
